### ISSUE TITLE
Fix errors in unit tests

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6167]
**Describe the bug**
We recently updated our useToggle hook and ToggleContext. As part of that, a lot of the unit tests were updated. However, some have warnings when run. We should fix these.

**To Reproduce**
Steps to reproduce the behaviour:

1. `yarn install`  `yarn run test:unit`
2. See errors and warnings:
for these unit tests `src/app/pages/ArticlePage/index.test.jsx` 
```
console.error
  Warning: An update to CanonicalMostRead inside a test was not wrapped in act(...).
  
  When testing, code that causes React state updates should be wrapped into act(...):
  
  act(() => {
    /* fire events that update state */
  });
  /* assert on the output */
  
  This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
      at CanonicalMostRead (/Users/covenj01/Sites/simorgh/src/app/containers/MostRead/Canonical/index.jsx:23:3)
      at MostReadContainer (/Users/covenj01/Sites/simorgh/src/app/containers/MostRead/index.jsx:15:3)
      at ArticlePage (/Users/covenj01/Sites/simorgh/src/app/pages/ArticlePage/ArticlePage.jsx:101:24)
      at Router (/Users/covenj01/Sites/simorgh/node_modules/react-router/cjs/react-router.js:99:30)
      at MemoryRouter (/Users/covenj01/Sites/simorgh/node_modules/react-router/cjs/react-router.js:187:35)
      at RequestContextProvider (/Users/covenj01/Sites/simorgh/src/app/contexts/RequestContext/index.jsx:27:3)
      at ServiceContextProvider (/Users/covenj01/Sites/simorgh/src/app/contexts/ServiceContext/__mocks__/index.jsx:13:3)
      at ToggleContextProvider (/Users/covenj01/Sites/simorgh/src/app/contexts/ToggleContext/index.jsx:10:34)
      at Context (/Users/covenj01/Sites/simorgh/src/app/pages/ArticlePage/index.test.jsx:31:20)

  45 |   }
  46 |
> 47 |   error(message, ...rest);
     |        ^
  48 | };
  49 |
```

**Expected behaviour**
We should have no such warnings when running our unit tests

**Screenshots**
```

```
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by joshcoventry** [comment]
These errors/warnings still appear in some of our unit tests.

For example, when `src/app/pages/ArticlePage/index.test.jsx` is run:


    console.error
      Warning: An update to CanonicalMostRead inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at CanonicalMostRead (/Users/covenj01/Sites/simorgh/src/app/containers/MostRead/Canonical/index.jsx:23:3)
          at MostReadContainer (/Users/covenj01/Sites/simorgh/src/app/containers/MostRead/index.jsx:15:3)
          at ArticlePage (/Users/covenj01/Sites/simorgh/src/app/pages/ArticlePage/ArticlePage.jsx:101:24)
          at Router (/Users/covenj01/Sites/simorgh/node_modules/react-router/cjs/react-router.js:99:30)
          at MemoryRouter (/Users/covenj01/Sites/simorgh/node_modules/react-router/cjs/react-router.js:187:35)
          at RequestContextProvider (/Users/covenj01/Sites/simorgh/src/app/contexts/RequestContext/index.jsx:27:3)
          at ServiceContextProvider (/Users/covenj01/Sites/simorgh/src/app/contexts/ServiceContext/__mocks__/index.jsx:13:3)
          at ToggleContextProvider (/Users/covenj01/Sites/simorgh/src/app/contexts/ToggleContext/index.jsx:10:34)
          at Context (/Users/covenj01/Sites/simorgh/src/app/pages/ArticlePage/index.test.jsx:31:20)

      45 |   }
      46 |
    > 47 |   error(message, ...rest);
         |        ^
      48 | };
      49 |
